# Generated by Django 4.0.1 on 2022-04-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=20)),
                ('d_mob', models.CharField(max_length=20)),
                ('d_email', models.CharField(max_length=20)),
                ('d_address', models.CharField(max_length=100)),
                ('d_district', models.CharField(max_length=20)),
                ('d_dob', models.CharField(max_length=20)),
                ('d_department', models.CharField(max_length=20)),
                ('d_gender', models.CharField(max_length=20)),
                ('d_datetime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='patient_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=20)),
                ('p_mob', models.CharField(max_length=20)),
                ('p_email', models.CharField(max_length=20)),
                ('p_address', models.CharField(max_length=100)),
                ('p_district', models.CharField(max_length=20)),
                ('p_dob', models.CharField(max_length=20)),
                ('p_age', models.CharField(max_length=20)),
                ('p_gender', models.CharField(max_length=20)),
                ('d_datetime', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
    ]
