# Generated by Django 4.0.1 on 2022-04-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0002_doctor_det_patient_det'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_det',
            name='d_datetime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_det',
            name='d_datetime',
            field=models.CharField(max_length=100),
        ),
    ]
