# Generated by Django 4.0.1 on 2022-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0003_alter_doctor_det_d_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_det',
            name='d_email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_det',
            name='p_email',
            field=models.CharField(max_length=100),
        ),
    ]
