# Generated by Django 4.0.1 on 2022-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0004_alter_doctor_det_d_email_alter_patient_det_p_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_det',
            name='d_password',
            field=models.CharField(default='Not approoved', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor_det',
            name='d_username',
            field=models.CharField(default='Not approoved', max_length=100),
        ),
    ]
