# Generated by Django 4.0.1 on 2022-04-24 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0005_doctor_det_d_password_doctor_det_d_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_det',
            name='d_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor_det',
            name='d_username',
            field=models.CharField(max_length=100),
        ),
    ]
