# Generated by Django 4.0.1 on 2022-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0006_alter_doctor_det_d_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient_det',
            name='p_password',
            field=models.CharField(default='Not approoved', max_length=100),
        ),
        migrations.AddField(
            model_name='patient_det',
            name='p_username',
            field=models.CharField(default='Not approoved', max_length=100),
        ),
    ]
