# Generated by Django 4.0.1 on 2022-04-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0007_patient_det_p_password_patient_det_p_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient_det',
            name='d_datetime',
        ),
        migrations.AddField(
            model_name='patient_det',
            name='p_datetime',
            field=models.CharField(default='3213', max_length=100),
        ),
    ]
