# Generated by Django 4.0.1 on 2022-04-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0008_remove_patient_det_d_datetime_patient_det_p_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_det',
            name='p_datetime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_det',
            name='p_password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_det',
            name='p_username',
            field=models.CharField(max_length=100),
        ),
    ]
