# Generated by Django 4.0.1 on 2022-04-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0009_alter_patient_det_p_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodbank_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=20)),
                ('b_num', models.CharField(max_length=20)),
                ('b_details', models.CharField(max_length=100)),
                ('b_username', models.CharField(max_length=100)),
                ('b_password', models.CharField(max_length=100)),
                ('b_datetime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bloodbank',
            },
        ),
        migrations.CreateModel(
            name='lab_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=20)),
                ('l_num', models.CharField(max_length=20)),
                ('l_details', models.CharField(max_length=100)),
                ('l_username', models.CharField(max_length=100)),
                ('l_password', models.CharField(max_length=100)),
                ('l_datetime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lab',
            },
        ),
        migrations.CreateModel(
            name='pharmacy_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_name', models.CharField(max_length=20)),
                ('ph_num', models.CharField(max_length=20)),
                ('ph_details', models.CharField(max_length=100)),
                ('ph_username', models.CharField(max_length=100)),
                ('ph_password', models.CharField(max_length=100)),
                ('ph_datetime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pharmacy',
            },
        ),
    ]
