# Generated by Django 4.0.1 on 2022-04-29 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ADMIN', '0010_bloodbank_det_lab_det_pharmacy_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='report_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=20)),
                ('r_details', models.CharField(max_length=100)),
                ('r_path', models.ImageField(upload_to='reports/')),
                ('r_date', models.CharField(max_length=20)),
                ('r_datetime', models.CharField(max_length=100)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.patient_det')),
            ],
            options={
                'db_table': 'lab_reports',
            },
        ),
    ]
