# Generated by Django 4.0.1 on 2022-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORY', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_det',
            name='r_addedby',
            field=models.CharField(default='2', max_length=20),
        ),
    ]
