# Generated by Django 4.0.1 on 2022-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LABORATORY', '0002_report_det_r_addedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_det',
            name='r_addedby',
            field=models.CharField(max_length=20),
        ),
    ]
