# Generated by Django 4.0.1 on 2022-04-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_name', models.CharField(max_length=20)),
                ('do_mob', models.CharField(max_length=20)),
                ('do_group', models.CharField(max_length=100)),
                ('do_address', models.CharField(max_length=100)),
                ('do_district', models.CharField(max_length=20)),
                ('do_dob', models.CharField(max_length=20)),
                ('do_age', models.CharField(max_length=20)),
                ('do_gender', models.CharField(max_length=20)),
                ('do_datetime', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'donor',
            },
        ),
    ]
