# Generated by Django 4.0.1 on 2022-04-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BLOOD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bldrec_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_group', models.CharField(max_length=20)),
                ('db_unit', models.CharField(max_length=20)),
                ('db_date', models.CharField(max_length=20)),
                ('do_datetime', models.CharField(max_length=100)),
                ('do_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BLOOD.donor_det')),
            ],
            options={
                'db_table': 'blood_received',
            },
        ),
    ]
