# Generated by Django 4.0.1 on 2022-04-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOOD', '0002_bldrec_det'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bldrec_det',
            name='do_datetime',
        ),
        migrations.AddField(
            model_name='bldrec_det',
            name='db_datetime',
            field=models.CharField(default='56', max_length=100),
        ),
        migrations.AlterField(
            model_name='bldrec_det',
            name='db_unit',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
