# Generated by Django 4.0.1 on 2022-04-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOOD', '0003_remove_bldrec_det_do_datetime_bldrec_det_db_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bldrec_det',
            name='db_datetime',
            field=models.CharField(max_length=100),
        ),
    ]
