# Generated by Django 4.0.1 on 2022-05-09 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ADMIN', '0010_bloodbank_det_lab_det_pharmacy_det'),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription_det',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pres', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('datetime', models.CharField(max_length=100)),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.doctor_det')),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ADMIN.patient_det')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
    ]
